### ISSUE TITLE
TypeError: Cannot read property 'typeName' of undefined

### ISSUE THREAD

**Issue by dalekurt** [kitajchuk/node-squarespace-server#75] opened 2015-02-09 17:42 UTC
I'm having this issue, `TypeError: Cannot read property 'typeName' of undefined` after reading another issue on this error message and that it was merged. I am still receiving it. Is there anything that I can as it related to my environment to fix it? I'm on Mac OS X (10.10.2)

```console
> sqs server
> sqs-server: Running site on localhost:5050
> sqs-server: AUTH - Login to Squarespace!
> sqs-server: GET - /

TypeError: Cannot read property 'typeName' of undefined
    at getTemplateKey (/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:298:35)
    at Object.renderTemplate (/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:334:23)
    at /usr/local/lib/node_modules/node-squarespace-server/squarespace-server.js:230:29
    at /usr/local/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-middleware/squarespace-middleware.js:290:13
    at Request._callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-middleware/squarespace-middleware.js:216:9)
    at Request.self.callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:344:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:1187:12)
```

**Comment by kitajchuk** [comment] 2015-02-09 18:16
To be certain, which version of the server are you using?

**Comment by dalekurt** [comment] 2015-02-09 18:20
Executing `sqs --version` does not return a value.

**Comment by kitajchuk** [comment] 2015-02-09 18:48
That's another bug, but I pushed a fix for that real quick :/

**Comment by kitajchuk** [comment] 2015-02-09 18:49
Also, which template are you using?

**Comment by dalekurt** [comment] 2015-02-09 18:52
The template is called `Bedford`

**Comment by kitajchuk** [comment] 2015-02-09 18:53
Ok, thanks man.

**Comment by adrienhobbs** [comment] 2015-02-10 17:16
Had the same problem @dalekurt.  Make sure you set a site wide password by going to settings -> security.  Then use this password as the password in your template.conf, not the password you use to login to Squarespace.

**Comment by kitajchuk** [comment] 2015-02-10 17:20
Ah, yeah. Sitewide password is separate from your Squarespace account password.

**Comment by kitajchuk** [comment] 2015-02-11 19:56
@dalekurt Was that the cause of your issue?

**Comment by shawn-northrop** [comment] 2015-02-19 21:41
I am having the same issue. I am able to load the local login screen but after logging in I am seeing this in the console:

    Cannot read property 'targetWebsite' of undefined
    at Request._callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-middleware/squarespace-middleware.js:108:22)
    at Request.self.callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:344:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:1187:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)

I am running sqs-server: 0.1.24 on OSX Yosemite

**Comment by shawn-northrop** [comment] 2015-02-19 21:47
I have tried using the sitewidepassword as described, I have also removed the sitewidepassword from squarespacesettings and template.conf. It fails both ways

**Comment by shawn-northrop** [comment] 2015-02-19 21:48
I am using the Marquee template

**Comment by shawn-northrop** [comment] 2015-02-19 21:53
Fixed the issue I was using http:// for the siteurl. This needs to be https://

**Comment by kitajchuk** [comment] 2015-02-20 06:47
Oh man, yeah. That's a good point out. The protocol for the siteurl must be https. Glad you figured it out.

**Closed** 2015-02-20 06:47 UTC
